#############################################################################
# Makefile for building: HandDetection
# Generated by qmake (2.01a) (Qt 4.8.5) on: do mrt. 27 21:48:08 2014
# Project:  HandDetection.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile HandDetection.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/gcc-4.2
CXX           = /usr/bin/g++-4.2
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 -Wall -W $(DEFINES)
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-g++ -I. -I. -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/libxml2 -I/usr/local/include -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/include -F/opt/local/Library/Frameworks -F/opt/local/lib
LINK          = /usr/bin/g++-4.2
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/opt/local/Library/Frameworks -F/opt/local/lib  -lxml2 -I/opt/local/include/libxml2/ -L/opt/local/include/ -ljpeg -lfftw3f -I/opt/local/lib -L/opt/local/lib -fopenmp -lopencv_nonfree -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video -lopencv_contrib -lopencv_objdetect -lopencv_legacy -lopencv_features2d -lopencv_ml -lopencv_flann -lopencv_calib3d -lopencv_gpu -I/opt/local/include -F/opt/local/Library/Frameworks -F/opt/local/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.6

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Mixture.cpp \
		JPEGImage.cpp \
		Model.cpp \
		HOGPyramid.cpp \
		Patchwork.cpp \
		Rectangle.cpp \
		Scene.cpp \
		Object.cpp \
		PersonDetection.cpp \
		main.cpp \
		DetBody.cpp \
		DetHand.cpp \
		SaveDetections.cpp \
		HighestLikelihood.cpp \
		Tracking.cpp \
		FaceDetection.cpp \
		Cluster.cpp 
OBJECTS       = Mixture.o \
		JPEGImage.o \
		Model.o \
		HOGPyramid.o \
		Patchwork.o \
		Rectangle.o \
		Scene.o \
		Object.o \
		PersonDetection.o \
		main.o \
		DetBody.o \
		DetHand.o \
		SaveDetections.o \
		HighestLikelihood.o \
		Tracking.o \
		FaceDetection.o \
		Cluster.o
DIST          = /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf \
		/opt/local/share/qt4/mkspecs/features/shared.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		HandDetection.pro
QMAKE_TARGET  = HandDetection
DESTDIR       = 
TARGET        = HandDetection

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CXXFLAGS = -pipe \
		-O2 \
		-Wall \
		-W
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HandDetection.pro  /opt/local/share/qt4/mkspecs/macx-g++/qmake.conf /opt/local/share/qt4/mkspecs/common/unix.conf \
		/opt/local/share/qt4/mkspecs/common/mac.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf \
		/opt/local/share/qt4/mkspecs/common/g++-base.conf \
		/opt/local/share/qt4/mkspecs/common/g++-macx.conf \
		/opt/local/share/qt4/mkspecs/qconfig.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri \
		/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/opt/local/share/qt4/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt4/mkspecs/features/qt_config.prf \
		/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt4/mkspecs/features/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt4/mkspecs/features/release.prf \
		/opt/local/share/qt4/mkspecs/features/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf \
		/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf \
		/opt/local/share/qt4/mkspecs/features/shared.prf \
		/opt/local/share/qt4/mkspecs/features/warn_on.prf \
		/opt/local/share/qt4/mkspecs/features/qt.prf \
		/opt/local/share/qt4/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt4/mkspecs/features/moc.prf \
		/opt/local/share/qt4/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt4/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt4/mkspecs/features/resources.prf \
		/opt/local/share/qt4/mkspecs/features/uic.prf \
		/opt/local/share/qt4/mkspecs/features/yacc.prf \
		/opt/local/share/qt4/mkspecs/features/lex.prf \
		/opt/local/share/qt4/mkspecs/features/include_source_dir.prf \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile HandDetection.pro
/opt/local/share/qt4/mkspecs/common/unix.conf:
/opt/local/share/qt4/mkspecs/common/mac.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base.conf:
/opt/local/share/qt4/mkspecs/common/gcc-base-macx.conf:
/opt/local/share/qt4/mkspecs/common/g++-base.conf:
/opt/local/share/qt4/mkspecs/common/g++-macx.conf:
/opt/local/share/qt4/mkspecs/qconfig.pri:
/opt/local/share/qt4/mkspecs/modules/qt_phonon.pri:
/opt/local/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/opt/local/share/qt4/mkspecs/features/qt_functions.prf:
/opt/local/share/qt4/mkspecs/features/qt_config.prf:
/opt/local/share/qt4/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt4/mkspecs/features/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt4/mkspecs/features/release.prf:
/opt/local/share/qt4/mkspecs/features/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_cxx.prf:
/opt/local/share/qt4/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt4/mkspecs/features/mac/split_sources.prf:
/opt/local/share/qt4/mkspecs/features/shared.prf:
/opt/local/share/qt4/mkspecs/features/warn_on.prf:
/opt/local/share/qt4/mkspecs/features/qt.prf:
/opt/local/share/qt4/mkspecs/features/unix/thread.prf:
/opt/local/share/qt4/mkspecs/features/moc.prf:
/opt/local/share/qt4/mkspecs/features/mac/rez.prf:
/opt/local/share/qt4/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt4/mkspecs/features/resources.prf:
/opt/local/share/qt4/mkspecs/features/uic.prf:
/opt/local/share/qt4/mkspecs/features/yacc.prf:
/opt/local/share/qt4/mkspecs/features/lex.prf:
/opt/local/share/qt4/mkspecs/features/include_source_dir.prf:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile HandDetection.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HandDetection1.0.0 || $(MKDIR) .tmp/HandDetection1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HandDetection1.0.0/ && $(COPY_FILE) --parents Mixture.h JPEGImage.h Model.h HOGPyramid.h Patchwork.h Rectangle.h SimpleOpt.h Scene.h Intersector.h Object.h PersonDetection.h Parameters.h DetBody.h DetHand.h SaveDetections.h HighestLikelihood.h Tracking.h FacedDetection.h Cluster.h .tmp/HandDetection1.0.0/ && $(COPY_FILE) --parents Mixture.cpp JPEGImage.cpp Model.cpp HOGPyramid.cpp Patchwork.cpp Rectangle.cpp Scene.cpp Object.cpp PersonDetection.cpp main.cpp DetBody.cpp DetHand.cpp SaveDetections.cpp HighestLikelihood.cpp Tracking.cpp FaceDetection.cpp Cluster.cpp .tmp/HandDetection1.0.0/ && (cd `dirname .tmp/HandDetection1.0.0` && $(TAR) HandDetection1.0.0.tar HandDetection1.0.0 && $(COMPRESS) HandDetection1.0.0.tar) && $(MOVE) `dirname .tmp/HandDetection1.0.0`/HandDetection1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HandDetection1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_cxx_make_all:
compiler_objective_cxx_clean:
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Mixture.o: Mixture.cpp Intersector.h \
		Rectangle.h \
		Mixture.h \
		Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Patchwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mixture.o Mixture.cpp

JPEGImage.o: JPEGImage.cpp JPEGImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JPEGImage.o JPEGImage.cpp

Model.o: Model.cpp Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o Model.cpp

HOGPyramid.o: HOGPyramid.cpp HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HOGPyramid.o HOGPyramid.cpp

Patchwork.o: Patchwork.cpp Patchwork.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Rectangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Patchwork.o Patchwork.cpp

Rectangle.o: Rectangle.cpp Rectangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rectangle.o Rectangle.cpp

Scene.o: Scene.cpp Scene.h \
		Object.h \
		Rectangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Scene.cpp

Object.o: Object.cpp Object.h \
		Rectangle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Object.o Object.cpp

PersonDetection.o: PersonDetection.cpp PersonDetection.h \
		SimpleOpt.h \
		Intersector.h \
		Rectangle.h \
		Mixture.h \
		Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Patchwork.h \
		Scene.h \
		Object.h \
		Parameters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PersonDetection.o PersonDetection.cpp

main.o: main.cpp DetBody.h \
		SimpleOpt.h \
		Intersector.h \
		Rectangle.h \
		Mixture.h \
		Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Patchwork.h \
		Scene.h \
		Object.h \
		PersonDetection.h \
		DetHand.h \
		SaveDetections.h \
		HighestLikelihood.h \
		FacedDetection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DetBody.o: DetBody.cpp DetBody.h \
		SimpleOpt.h \
		Intersector.h \
		Rectangle.h \
		Mixture.h \
		Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Patchwork.h \
		Scene.h \
		Object.h \
		PersonDetection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetBody.o DetBody.cpp

DetHand.o: DetHand.cpp DetHand.h \
		SimpleOpt.h \
		Intersector.h \
		Rectangle.h \
		Mixture.h \
		Model.h \
		HOGPyramid.h \
		JPEGImage.h \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/Sparse \
		Eigen/SparseCore \
		Eigen/src/SparseCore/SparseUtil.h \
		Eigen/src/SparseCore/SparseMatrixBase.h \
		Eigen/src/SparseCore/CompressedStorage.h \
		Eigen/src/SparseCore/AmbiVector.h \
		Eigen/src/SparseCore/SparseMatrix.h \
		Eigen/src/SparseCore/MappedSparseMatrix.h \
		Eigen/src/SparseCore/SparseVector.h \
		Eigen/src/SparseCore/CoreIterators.h \
		Eigen/src/SparseCore/SparseBlock.h \
		Eigen/src/SparseCore/SparseTranspose.h \
		Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
		Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
		Eigen/src/SparseCore/SparseDot.h \
		Eigen/src/SparseCore/SparsePermutation.h \
		Eigen/src/SparseCore/SparseAssign.h \
		Eigen/src/SparseCore/SparseRedux.h \
		Eigen/src/SparseCore/SparseFuzzy.h \
		Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
		Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
		Eigen/src/SparseCore/SparseProduct.h \
		Eigen/src/SparseCore/SparseDenseProduct.h \
		Eigen/src/SparseCore/SparseDiagonalProduct.h \
		Eigen/src/SparseCore/SparseTriangularView.h \
		Eigen/src/SparseCore/SparseSelfAdjointView.h \
		Eigen/src/SparseCore/TriangularSolver.h \
		Eigen/src/SparseCore/SparseView.h \
		Eigen/OrderingMethods \
		Eigen/src/OrderingMethods/Amd.h \
		Eigen/src/Core/util/NonMPL2.h \
		Eigen/SparseCholesky \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/SparseSolve.h \
		Eigen/src/SparseCholesky/SimplicialCholesky.h \
		Eigen/IterativeLinearSolvers \
		Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
		Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
		Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
		Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
		Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
		Patchwork.h \
		Scene.h \
		Object.h \
		PersonDetection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetHand.o DetHand.cpp

SaveDetections.o: SaveDetections.cpp SaveDetections.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SaveDetections.o SaveDetections.cpp

HighestLikelihood.o: HighestLikelihood.cpp HighestLikelihood.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HighestLikelihood.o HighestLikelihood.cpp

Tracking.o: Tracking.cpp Tracking.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tracking.o Tracking.cpp

FaceDetection.o: FaceDetection.cpp FacedDetection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FaceDetection.o FaceDetection.cpp

Cluster.o: Cluster.cpp Cluster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cluster.o Cluster.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

